spring:
  application:
    name: fastfood
  datasource:
    url: ${FASTFOOD_JDBC_URL}
    username: ${FASTFOOD_DB_USER}
    password: ${FASTFOOD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
external:
  api:
    url: ${PAGAMENTOAPI_URL}
  order:
    url: ${PEDIDOAPI_URL}
  cache:
    order:
      url: ${CACHE_PEDIDOAPI_URL}
server:
  servlet:
    context-path: /fastfood
