apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  serviceName: "postgresdb"
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: FASTFOOD_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: FASTFOOD_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: FASTFOOD_DB_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: banco-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: banco-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi