apiVersion: v1
kind: Service
metadata:
  name: fastfood-payments-service
spec:
  type: NodePort
  selector:
    app: fastfood-payments
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001